import { getProjectGasSpend, getTotalGasSpend, getMultisigGasSpend } from 'lib'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers'
import TerminalV1_1 from "@jbx-protocol/contracts-v1/deployments/mainnet/TerminalV1_1.json";
const JBXInterface = new ethers.utils.Interface(TerminalV1_1.abi);

const Home: NextPage = () => {
    const [txs, setTxs] = useState('')
    const [input, setGasInput] = useState('')
    const [startBlock, setStartBlock] = useState('')
    const [endBlock, setEndBlock] = useState('')

    const handleGasSpend = async () => {
        const gasSpend = await getProjectGasSpend({ startblock: '0', endblock: '999999999', abi: TerminalV1_1.abi })
        setTxs(gasSpend)
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <label>ABI</label>
                <textarea onChange={(e) => setGasInput(e.target.value)} />
                <br />
                <label>startblock (defaults to 0)</label>
                <input onChange={(e) => setStartBlock(e.target.value)} />
                <br />
                <label>endblock (defaults to 0)</label>
                <input onChange={(e) => setEndBlock(e.target.value)} />
                <label>pay function name</label>
                <input onChange={(e) => setEndBlock(e.target.value)} />
                <label>terminal address (multisig)</label>
                <input onChange={(e) => setEndBlock(e.target.value)} />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
